// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using RCM.SpeedSMS;
//
//    var sendSms = SendSms.FromJson(jsonString);

namespace RCM.SpeedSMS
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class SendSms
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("code")]
        public string Code { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("tranId")]
        public long TranId { get; set; }

        [JsonProperty("totalSMS")]
        public long TotalSms { get; set; }

        [JsonProperty("totalPrice")]
        public long TotalPrice { get; set; }

        [JsonProperty("invalidPhone")]
        public object[] InvalidPhone { get; set; }
    }

    public partial class SendSms
    {
        public static SendSms FromJson(string json) => JsonConvert.DeserializeObject<SendSms>(json, RCM.SpeedSMS.Converter.Settings);
    }
}
